### PR TITLE
feat(typescript): migrate to typescript

### LINKED ISSUE #221: migrate to typescript or add typescript defs?
are you willing to add typescript support to this package?

### PR DESCRIPTION
**Pull request by AugustoCalaca**
* improve dx with typescript IntelliSense
* add  type safe to repo
 
closes #221

### CODE REVIEW

**Comment by AugustoCalaca** [comment]
ping friendly @taion

**Comment by taion** [comment]
hi! i've been quite busy this week – i'll try to look over the coming weekend

**Comment by taion** [comment]
cleaned this up a little bit to more closely match the rest of our TS tooling

**Comment by taion** [comment]
published as v0.3.0

**Pull request merged**
