### PR TITLE
Upgrade to GraphQL v16

### PR DESCRIPTION
**Pull request by fersilva16**

### CODE REVIEW

**Review by sibelius — APPROVED** [review]
this solves for us

**Comment by taion** [comment]
@sibelius I've added you to this repo and to the npm registry. Feel free to do whatever you need. I'd also be happy to transfer ownership of this package to you or to others, cc @jquense

**Comment by sibelius** [comment]
You can transfer to me or my company entria, and we keep this package up to date

I don't think it needs more features

**Comment by noghartt** [comment]
> @sibelius I've added you to this repo and to the npm registry. Feel free to do whatever you need. I'd also be happy to transfer ownership of this package to you or to others, cc @jquense

Could we also merge `graphql-relay-subscription` into `graphql-relay-js`, I write an issue giving this suggestion on [graphql-relay-js](https://github.com/graphql/graphql-relay-js/issues/376).

**Comment by taion** [comment]
That would be up to the maintainers of that package, I guess.

**Comment by jquense** [comment]
@taion please add me here and to npm 👍

**Pull request merged**
